# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3c9607b628bf4e62bbf707eca9ebd67b86ef3c27ba18daef2160a02bcc6f9edb34d750d1f2608eace2c8e32cd94072f6dfcbf3f104379138d45bab5450da1e2

test:
  secret_key_base: 1a3a83f5ec83a2a949fcfd240a6dff6d898b0aa8d28dff92aad4ff5e5c19cd93d0833d24826fd8e73287796f472b317750a8db5beed777d52f9579dcbf0317e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
